/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{html,ts}",
  ],
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed": "#64320e",
        "tertiary-fixed-dim": "#f0e9c3",
        "on-background": "#4d2821",
        "primary-container": "#feabaa",
        "on-error-container": "#671200",
        "on-tertiary-fixed": "#504c30",
        "on-secondary-container": "#7b431f",
        "error-dim": "#821a01",
        "error": "#aa371c",
        "on-tertiary-fixed-variant": "#6d694a",
        "surface-container-lowest": "#ffffff",
        "secondary": "#8b502a",
        "primary-fixed": "#feabaa",
        "on-primary": "#fff7f6",
        "on-primary-fixed-variant": "#6e3334",
        "on-surface": "#4d2821",
        "on-tertiary-container": "#625e40",
        "surface-tint": "#8d4c4c",
        "secondary-fixed": "#ffdbc8",
        "on-primary-container": "#642b2c",
        "surface-variant": "#ffdad4",
        "inverse-surface": "#1b0906",
        "tertiary-container": "#fef7d0",
        "on-error": "#fff7f6",
        "outline": "#a06e65",
        "on-tertiary": "#fff9e2",
        "secondary-container": "#ffdbc8",
        "on-secondary-fixed-variant": "#874d27",
        "surface": "#fff8f6",
        "on-secondary": "#fff7f5",
        "background": "#fff8f6",
        "surface-container-high": "#ffe2dd",
        "surface-container": "#ffe9e5",
        "tertiary": "#646042",
        "surface-dim": "#ffcfc6",
        "secondary-dim": "#7c4520",
        "surface-bright": "#fff8f6",
        "inverse-on-surface": "#b8958f",
        "primary": "#8d4c4c",
        "on-primary-fixed": "#491618",
        "secondary-fixed-dim": "#ffc9ab",
        "surface-container-low": "#fff0ee",
        "on-surface-variant": "#81534b",
        "primary-dim": "#7f4141",
        "outline-variant": "#dda49a",
        "inverse-primary": "#fba8a7",
        "primary-fixed-dim": "#ef9e9d",
        "tertiary-dim": "#585437",
        "error-container": "#fa7150",
        "surface-container-highest": "#ffdad4",
        "custom-active": "#FFB284",
        "custom-timeline": "#C6C09C"
      }
    },
  },
  plugins: [],
}

